// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define cmdApplicationMenu 600 
#define IDC_TABMAIN 1001 
#define IDC_TABMAIN_LabelTitle_RESID 1001
#define cmdGroupMain 1002 
#define cmdGroupMain_LabelTitle_RESID 1002
#define IDC_TABTABLE 1003 
#define IDC_TABTABLE_LabelTitle_RESID 1003
#define IDC_TABDESIGN 1004 
#define IDC_TABDESIGN_LabelTitle_RESID 1004
#define IDC_TABLAYOUT 1005 
#define IDC_TABLAYOUT_LabelTitle_RESID 1005
#define cmdGroupDesign 1006 
#define cmdGroupDesign_LabelTitle_RESID 1006
#define cmdGroupLayout 1007 
#define cmdGroupLayout_LabelTitle_RESID 1007
#define IDC_SELECT 1050 
#define IDC_SELECT_LabelTitle_RESID 1050
#define IDC_SELECT_LabelDescription_RESID 1051
#define IDC_SELECT_TooltipTitle_RESID 1052
#define IDC_SELECT_TooltipDescription_RESID 1053
#define IDC_SELECT_LargeImages_RESID 150
#define IDC_UNSELECT 1060 
#define IDC_UNSELECT_LabelTitle_RESID 1060
#define IDC_UNSELECT_LabelDescription_RESID 1061
#define IDC_UNSELECT_TooltipTitle_RESID 1062
#define IDC_UNSELECT_TooltipDescription_RESID 1063
#define IDC_UNSELECT_LargeImages_RESID 160
#define IDC_DESIGN1 1010 
#define IDC_DESIGN1_LabelTitle_RESID 1010
#define IDC_DESIGN1_LargeImages_RESID 110
#define IDC_DESIGN2 1011 
#define IDC_DESIGN2_LabelTitle_RESID 1011
#define IDC_DESIGN2_LargeImages_RESID 111
#define IDC_DESIGN3 1012 
#define IDC_DESIGN3_LabelTitle_RESID 10112
#define IDC_DESIGN3_LargeImages_RESID 112
#define IDC_LAYOUT1 1013 
#define IDC_LAYOUT1_LabelTitle_RESID 1013
#define IDC_LAYOUT1_LargeImages_RESID 113
#define IDC_LAYOUT2 1014 
#define IDC_LAYOUT2_LabelTitle_RESID 1014
#define IDC_LAYOUT2_LargeImages_RESID 114
#define IDC_TABCOLOR 1999 
#define IDC_TABCOLOR_LabelTitle_RESID 1999
#define cmdButtonsGroup 2000 
#define cmdButtonsGroup_LabelTitle_RESID 2000
#define cmdDropDownColorPickerGroup 2001 
#define cmdDropDownColorPickerGroup_LabelTitle_RESID 2001
#define IDC_COLORTHEME 2002 
#define IDC_COLORTHEME_LabelTitle_RESID 2002
#define IDC_COLORTHEME_LargeImages_RESID 202
#define IDC_COLORSTD 2003 
#define IDC_COLORSTD_LabelTitle_RESID 2003
#define IDC_COLORSTD_LargeImages_RESID 203
#define IDC_CLRHILITE 204 
#define IDC_CLRHILITE_LabelTitle_RESID 2004
#define IDC_CLRHILITE_LargeImages_RESID 204
#define IDC_LISTCOLORS 2006 
#define IDC_LISTCOLORS_LabelTitle_RESID 2006
#define IDC_LISTCOLORS_LargeImages_RESID 206
#define IDC_NEW 7001 
#define IDC_NEW_LabelTitle_RESID 7001
#define IDC_NEW_LabelDescription_RESID 7002
#define IDC_NEW_TooltipTitle_RESID 7003
#define IDC_NEW_TooltipDescription_RESID 7004
#define IDC_NEW_SmallImages_RESID 701
#define IDC_NEW_LargeImages_RESID 702
#define IDC_OPEN 8000 
#define IDC_OPEN_LabelTitle_RESID 8000
#define IDC_OPEN_LabelDescription_RESID 8001
#define IDC_OPEN_TooltipTitle_RESID 8002
#define IDC_OPEN_TooltipDescription_RESID 8003
#define IDC_OPEN_SmallImages_RESID 801
#define IDC_OPEN_LargeImages_RESID 800
#define IDC_SAVE 9000 
#define IDC_SAVE_LabelTitle_RESID 9100
#define IDC_SAVE_LabelDescription_RESID 9001
#define IDC_SAVE_TooltipTitle_RESID 9002
#define IDC_SAVE_TooltipDescription_RESID 9003
#define IDC_SAVE_SmallImages_RESID 901
#define IDC_SAVE_LargeImages_RESID 900
#define IDC_SAVEAS 9101 
#define IDC_SAVEAS_LabelTitle_RESID 9102
#define IDC_SAVEAS_TooltipDescription_RESID 9103
#define IDC_SAVEAS_SmallImages_RESID 9104
#define IDC_SAVEAS_LargeImages_RESID 9105
#define IDC_SAVEASMORE 9106 
#define CmdHeaderSave 9107 
#define CmdHeaderSave_LabelTitle_RESID 9108
#define IDC_RTF 9109 
#define IDC_RTF_LabelTitle_RESID 9110
#define IDC_RTF_LabelDescription_RESID 9111
#define IDC_RTF_SmallImages_RESID 9112
#define IDC_RTF_LargeImages_RESID 9113
#define IDC_OPENXML 9114 
#define IDC_OPENXML_LabelTitle_RESID 9115
#define IDC_OPENXML_LabelDescription_RESID 9116
#define IDC_OPENXML_SmallImages_RESID 9117
#define IDC_OPENXML_LargeImages_RESID 9118
#define IDC_ODF 9119 
#define IDC_ODF_LabelTitle_RESID 9120
#define IDC_ODF_LabelDescription_RESID 9121
#define IDC_ODF_SmallImages_RESID 9122
#define IDC_ODF_LargeImages_RESID 9123
#define IDC_TXT 9214 
#define IDC_TXT_LabelTitle_RESID 9125
#define IDC_TXT_LabelDescription_RESID 9126
#define IDC_TXT_SmallImages_RESID 9127
#define IDC_TXT_LargeImages_RESID 9128
#define IDC_FMTOTHER 9129 
#define IDC_FMTOTHER_LabelTitle_RESID 9130
#define IDC_FMTOTHER_LabelDescription_RESID 9131
#define IDC_FMTOTHER_SmallImages_RESID 9132
#define IDC_FMTOTHER_LargeImages_RESID 9133
#define IDC_EXIT 20000 
#define IDC_EXIT_LabelTitle_RESID 20000
#define IDC_EXIT_LabelDescription_RESID 20001
#define IDC_EXIT_TooltipTitle_RESID 20002
#define IDC_EXIT_TooltipDescription_RESID 10003
#define IDC_EXIT_SmallImages_RESID 22221
#define IDC_EXIT_LargeImages_RESID 22220
#define cmdGroupFileActions 355 
#define cmdGroupFileActions_LabelTitle_RESID 355
#define cmdQAT 306 
#define cmdCustomizeQAT 307 
#define cmdRecentItems 1775 
#define cmdRecentItems_LabelTitle_RESID 1776
#define cmdGroupRichFont 1777 
#define cmdGroupRichFont_LabelTitle_RESID 1778
#define IDC_RICHFONT 1779 
#define IDC_RICHFONT_Keytip_RESID 1780
#define IDC_TOGGLE1 1778 
#define IDC_TOGGLE1_LabelTitle_RESID 3260
#define IDC_TOGGLE1_SmallImages_RESID 3262
#define IDC_TOGGLE1_LargeImages_RESID 3261
#define cmdGroup4 2 
#define cmdFileMenu 3 
#define cmdMRUList 4 
#define cmdMRUList_LabelTitle_RESID 3285
#define cmdGroup6 5 
#define IDC_EDITDROPDOWN 6 
#define IDC_EDITDROPDOWN_LabelTitle_RESID 3386
#define IDC_EDITDROPDOWN_LargeImages_RESID 3387
#define IDC_RIBBONHELP 27664 
#define IDC_OPENFILEMORE 20500 
#define IDC_OPENFILE 27601 
#define IDC_OPENFILE_LabelTitle_RESID 2522
#define IDC_OPENFILE_LabelDescription_RESID 2523
#define IDC_OPENFILE_LargeImages_RESID 4517
#define IDC_OPENURL 22774 
#define IDC_OPENURL_LabelTitle_RESID 2524
#define IDC_OPENURL_LabelDescription_RESID 2525
#define IDC_OPENURL_LargeImages_RESID 4518
#define IDC_PRINTMORE 20501 
#define CmdHeaderPrint 20511 
#define CmdHeaderPrint_LabelTitle_RESID 2537
#define IDC_PRINT 27607 
#define IDC_PRINT_LabelTitle_RESID 2533
#define IDC_PRINT_LabelDescription_RESID 2528
#define IDC_PRINT_LargeImages_RESID 4521
#define IDC_PRINTSETUP 17606 
#define IDC_PRINTSETUP_LabelTitle_RESID 2529
#define IDC_PRINTSETUP_LabelDescription_RESID 2530
#define IDC_PRINTSETUP_LargeImages_RESID 2531
#define IDC_QUICKPRINT 2532 
#define IDC_QUICKPRINT_LabelTitle_RESID 3133
#define IDC_QUICKPRINT_LabelDescription_RESID 2534
#define IDC_QUICKPRINT_LargeImages_RESID 2535
#define IDC_PRINTPREVIEW 2536 
#define IDC_PRINTPREVIEW_LabelTitle_RESID 3137
#define IDC_PRINTPREVIEW_LabelDescription_RESID 2538
#define IDC_PRINTPREVIEW_LargeImages_RESID 2539
#define cmdTab1 7  /* These comments are optional and are inserted into the header file. */ 
#define cmdTab1_LabelTitle_RESID 7200
#define cmdGroup1 8  /* Group #1 */ 
#define cmdGroup1_SmallImages_RESID 7250
#define IDC_CMD_CONTEXT1 30071  /* Button that activates context 1 */ 
#define IDC_CMD_CONTEXT1_LabelTitle_RESID 7201
#define IDC_CMD_CONTEXT1_LargeImages_RESID 7251
#define IDC_CMD_CONTEXT2 30072  /* Button that activates context 2 */ 
#define IDC_CMD_CONTEXT2_LabelTitle_RESID 7202
#define IDC_CMD_CONTEXT2_LargeImages_RESID 7252
#define IDC_CMD_CONTEXT3 30073  /* Button that activates context 3 */ 
#define IDC_CMD_CONTEXT3_LabelTitle_RESID 7203
#define IDC_CMD_CONTEXT3_LargeImages_RESID 7253
#define IDC_CMD_CONTEXT4 30074  /* Button that activates context 4 */ 
#define IDC_CMD_CONTEXT4_LabelTitle_RESID 7204
#define IDC_CMD_CONTEXT4_LargeImages_RESID 7254
#define IDC_CUT 64  /* Cut button */ 
#define IDC_CUT_LabelTitle_RESID 7205
#define IDC_CUT_TooltipTitle_RESID 23111
#define IDC_CUT_TooltipDescription_RESID 23112
#define IDC_CUT_SmallImages_RESID 7255
#define IDC_COPY 23116  /* Copy button */ 
#define IDC_COPY_LabelTitle_RESID 7206
#define IDC_COPY_TooltipTitle_RESID 23114
#define IDC_COPY_TooltipDescription_RESID 23115
#define IDC_COPY_SmallImages_RESID 7256
#define IDC_PASTE 23117  /* Paste button */ 
#define IDC_PASTE_LabelTitle_RESID 7207
#define IDC_PASTE_TooltipTitle_RESID 23118
#define IDC_PASTE_TooltipDescription_RESID 23119
#define IDC_PASTE_SmallImages_RESID 23120
#define IDC_CTXTOGGLE 9  /* Toggle Button */ 
#define IDC_CTXTOGGLE_LabelTitle_RESID 7208
#define IDC_CTXTOGGLE_SmallImages_RESID 7258
#define IDC_BUTTON1 24161  /* Button #1 */ 
#define IDC_BUTTON1_LabelTitle_RESID 7209
#define IDC_BUTTON1_LargeImages_RESID 7259
#define IDC_BUTTON2 21161  /* Button #2 */ 
#define IDC_BUTTON2_LabelTitle_RESID 7210
#define IDC_BUTTON2_LargeImages_RESID 7260
#define IDC_BUTTON3 21163  /* Button #3 */ 
#define IDC_BUTTON3_LabelTitle_RESID 7211
#define IDC_BUTTON3_LargeImages_RESID 7261
#define IDC_BUTTONS 21165  /* DropDownButton that contains the three buttons */ 
#define IDC_BUTTONS_LabelTitle_RESID 7212
#define IDC_BUTTONS_LargeImages_RESID 7262
#define IDC_CMD_CONTEXTMAP1 10  /* the Context Map for Context 1 */ 
#define IDC_CMD_CONTEXTMAP2 11  /* the Context Map for Context 2 */ 
#define IDC_CMD_CONTEXTMAP3 12  /* the Context Map for Context 3 */ 
#define IDC_CMD_CONTEXTMAP4 13  /* the Context Map for Context 4 */ 
#define IDC_CHECK1 76 
#define IDC_CHECK1_LabelTitle_RESID 25
#define IDC_CHECK1_LabelDescription_RESID 26
#define IDC_CHECK1_TooltipTitle_RESID 27
#define IDC_CHECK1_TooltipDescription_RESID 28
#define cmdCheck2 77 
#define cmdCheck2_LabelTitle_RESID 31
#define cmdCheck2_LabelDescription_RESID 32
#define cmdCheck2_TooltipTitle_RESID 33
#define cmdCheck2_TooltipDescription_RESID 34
#define cmdCheckHdr 78 
#define cmdCheckHdr_TooltipTitle_RESID 39
#define cmdCheckHdr_TooltipDescription_RESID 38
#define IDC_PARAGRAPH 79 
#define IDC_PARAGRAPH_LabelTitle_RESID 41
#define IDC_PARAGRAPH_SmallImages_RESID 40
#define IDC_INDENT 80 
#define IDC_INDENT_LabelTitle_RESID 42
#define IDC_INDENT_TooltipTitle_RESID 43
#define IDC_INDENT_TooltipDescription_RESID 44
#define IDC_INDENT_SmallImages_RESID 45
#define IDC_OUTDENT 81 
#define IDC_OUTDENT_LabelTitle_RESID 46
#define IDC_OUTDENT_TooltipTitle_RESID 47
#define IDC_OUTDENT_TooltipDescription_RESID 48
#define IDC_OUTDENT_SmallImages_RESID 49
#define IDC_LINESPACING 82 
#define IDC_LINESPACING_LabelTitle_RESID 50
#define IDC_LINESPACING_TooltipTitle_RESID 51
#define IDC_LINESPACING_TooltipDescription_RESID 52
#define IDC_LINESPACING_SmallImages_RESID 4720
#define IDC_LINESPACE1 83 
#define IDC_LINESPACE1_LabelTitle_RESID 60
#define IDC_LINESPACE115 84 
#define IDC_LINESPACE115_LabelTitle_RESID 61
#define IDC_LINESPACE15 85 
#define IDC_LINESPACE15_LabelTitle_RESID 53
#define IDC_LINESPACE2 86 
#define IDC_LINESPACE2_LabelTitle_RESID 54
#define IDC_ALIGNLEFT 87 
#define IDC_ALIGNLEFT_LabelTitle_RESID 56
#define IDC_ALIGNLEFT_TooltipTitle_RESID 57
#define IDC_ALIGNLEFT_TooltipDescription_RESID 58
#define IDC_ALIGNLEFT_SmallImages_RESID 59
#define IDC_ALIGNRIGHT 88 
#define IDC_ALIGNRIGHT_LabelTitle_RESID 89
#define IDC_ALIGNRIGHT_TooltipTitle_RESID 90
#define IDC_ALIGNRIGHT_TooltipDescription_RESID 91
#define IDC_ALIGNRIGHT_SmallImages_RESID 92
#define IDC_ALIGNCENTER 4733 
#define IDC_ALIGNCENTER_LabelTitle_RESID 4730
#define IDC_ALIGNCENTER_TooltipTitle_RESID 4731
#define IDC_ALIGNCENTER_TooltipDescription_RESID 4732
#define IDC_ALIGNCENTER_SmallImages_RESID 4734
#define IDC_JUSTIFY 4738 
#define IDC_JUSTIFY_LabelTitle_RESID 4735
#define IDC_JUSTIFY_TooltipTitle_RESID 4736
#define IDC_JUSTIFY_TooltipDescription_RESID 4737
#define IDC_JUSTIFY_SmallImages_RESID 4739
#define IDC_MORE 21151 
#define IDC_MORE_LabelTitle_RESID 21149
